### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by kynx** [metalinspired/laminas-dkim#7]
Hi @metalinspired I don't want to be rude or hasty, but are you still interested in maintaining this library?

I've been uncovering and fixing a number of [bugs](https://github.com/kynx/laminas-dkim/issues?q=is%3Aissue+label%3Abug) on my fork that were causing it to generate invalid signatures, plus cleaning things up, adding tests and a couple of new features. I need a working version, so went ahead and published it on packagist yesterday.

If you're OK with that, can you mark this library as abandoned on packagist and point users to [kynx/laminas-dkim](https://github.com/kynx/laminas-dkim)?

**Comment by metalinspired** [comment]
Hi, and than you very much.
No, not abandoned, just neck deep in work.
Hopefully I'll find time over the week.
